<?php

$modversion['name'] = _ALBM_FLASHGAMES_NAME;
$modversion['version'] = '0.9';
$modversion['description'] = _ALBM_FLASHGAMES_DESC;
$modversion['author'] = 'Oliver Kaufhold (aka gripsmaker) <br> (http://www.tipsmitgrips.de)';
$modversion['credits'] = "Lee Eason<br>(http://www.pnflashgames.com)<br>

Daniel Branco<br>(http://bluetopia.homeip.net)<br>Kazumi Ono<br>( http://www.mywebaddons.com/ )<br>The XOOPS Project <br> and all 'Flashgames' Supporters!";
$modversion['help'] = 'mylinks.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 0;
$modversion['image'] = 'images/mylinks_slogo.gif';
$modversion['dirname'] = 'flashgames';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'flashgames_cat';
$modversion['tables'][1] = 'flashgames_games';
$modversion['tables'][2] = 'flashgames_text';
$modversion['tables'][3] = 'flashgames_votedata';
$modversion['tables'][4] = 'flashgames_comments';
$modversion['tables'][5] = 'flashgames_score';
$modversion['tables'][6] = 'flashgames_savedGames';

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu'] = 'admin/menu.php';

// Blocks
$modversion['blocks'][1]['file'] = 'flashgames_game.php';
$modversion['blocks'][1]['name'] = _ALBM_MYGAME_ALBUM;
$modvertion['blocks'][1]['description'] = 'Shows a random game';
$modversion['blocks'][1]['show_func'] = 'b_flashgames_game_show';
$modversion['blocks'][1]['edit_func'] = 'b_flashgames_game_edit';
$modversion['blocks'][1]['options'] = 'width|100';

$modversion['blocks'][2]['file'] = 'flashgames_top.php';
$modversion['blocks'][2]['name'] = _ALBM_MYLINKS_BNAME1;
$modvertion['blocks'][2]['description'] = 'Shows recently added games';
$modversion['blocks'][2]['show_func'] = 'b_flashgames_top_show';
$modversion['blocks'][2]['edit_func'] = 'b_flashgames_top_edit';
$modversion['blocks'][2]['options'] = 'date|10';
$modversion['blocks'][2]['template'] = 'flashgames_block_new.html';

$modversion['blocks'][3]['file'] = 'flashgames_top.php';
$modversion['blocks'][3]['name'] = _ALBM_MYLINKS_BNAME2;
$modvertion['blocks'][3]['description'] = 'Shows most viewed games';
$modversion['blocks'][3]['show_func'] = 'b_flashgames_top_show';
$modversion['blocks'][3]['edit_func'] = 'b_flashgames_top_edit';
$modversion['blocks'][3]['options'] = 'hits|10';
$modversion['blocks'][3]['template'] = 'flashgames_block_top.html';

$modversion['blocks'][4]['file'] = 'flashgames_comments.php';
$modversion['blocks'][4]['name'] = _ALBM_MYGAME_COMMENTS;
$modvertion['blocks'][4]['description'] = 'Shows last comments';
$modversion['blocks'][4]['show_func'] = 'b_flashgames_comments_show';
$modversion['blocks'][4]['edit_func'] = 'b_flashgames_comments_edit';
$modversion['blocks'][4]['options'] = '10|1';

$modversion['blocks'][5]['file'] = 'flashgames_top.php';
$modversion['blocks'][5]['name'] = _ALBM_MYLINKS_BNAME3;
$modvertion['blocks'][5]['description'] = 'Shows best players';
$modversion['blocks'][5]['show_func'] = 'b_flashgames_topplayer_show';
$modversion['blocks'][5]['edit_func'] = 'b_flashgames_topplayer_edit';
$modversion['blocks'][5]['options'] = '10';
$modversion['blocks'][5]['template'] = 'flashgames_block_topplayer.html';

// Menu
$modversion['hasMain'] = 1;
// please activate if you want to let user submit games
//$modversion['sub'][1]['name'] = _ALBM_MYLINKS_SMNAME1;
//$modversion['sub'][1]['url'] = "submit.php";

$modversion['sub'][2]['name'] = _ALBM_MYLINKS_SMNAME4;
$modversion['sub'][2]['url'] = 'highscores.php';
$modversion['sub'][3]['name'] = _ALBM_MYLINKS_SMNAME2;
$modversion['sub'][3]['url'] = 'topten.php?hit=1';
$modversion['sub'][4]['name'] = _ALBM_MYLINKS_SMNAME3;
$modversion['sub'][4]['url'] = 'topten.php?rate=1';

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/search.inc.php';
$modversion['search']['func'] = 'flashgames_search';

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['itemName'] = 'lid';
$modversion['comments']['pageName'] = 'game.php';

// Templates
$modversion['templates'][1]['file'] = 'flashgames_game.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'flashgames_gameformat.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'flashgames_highscores.html';
$modversion['templates'][3]['description'] = 'Highscores';
